### ISSUE TITLE
https://excubo-ag.github.io/Blazor.Grids/

### ISSUE THREAD

**Issue by sajrashid** [excubo-ag/Blazor.Grids#18] opened 2022-02-08 10:42 UTC
demo site failing 

blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at St (blazor.webassembly.js:1:59395)
window.Module.s.printErr @ blazor.webassembly.js:1

**Comment by stefanloerwald** [comment] 2022-02-08 10:51
I can't reproduce that on my device. Can you please try clearing your cache?

**Comment by sajrashid** [comment] 2022-02-08 11:28
HI @stefanloerwald, no joy clearing cache, 

**showing verify integrity errors
blazor.webassembly.js:1          GET https://excubo-ag.github.io/Blazor.Grids/_framework/Microsoft.AspNetCore.Components.WebAssembly.dll net::ERR_CONNECTION_CLOSED 200**

fiddler reveals a bit more
`fiddler.network.https> HTTPS handshake to excubo-ag.github.io (for #8) failed. System.IO.IOException Authentication failed because the remote party has closed the transport stream.`


it does smell like a local problem, I'll report back if I find anything else

**Comment by sajrashid** [comment] 2022-02-08 11:33
Update Edge&Brave, both connection refused

Edge also shows (probably not related tho)
```
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
/Blazor.Grids/:1 
       GET https://excubo-ag.github.io/Blazor.Grids/ net::ERR_CONNECTION_CLOSED 200
```

**Comment by stefanloerwald** [comment] 2022-02-08 11:38
I checked with yet another device and no issues for me... Not sure what I can do about this, sorry.

**Comment by stefanloerwald** [comment] 2022-02-10 17:29
Closing since it's not reproducible on multiple devices.

**Closed as completed by stefanloerwald** 2022-02-10 17:29 UTC
